# --- Configuración de Fuente ---
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# --- Diseño y Apariencia ---
window_padding_width 15
background_opacity   0.70
background_blur      1

# --- Colores Basados en el Nuevo Logo Neón (Negro Puro y Neones) ---
background            #000000
foreground            #FFFFFF
cursor                #00FFFF
selection_background  #333333
selection_foreground  #FFFFFF

# Colores del Terminal (Inspirados en el degradado del logo)
# Negro
color0 #000000
color8 #444444

# Rojo / Rosa (Logo Right)
color1 #FF007F
color9 #FF007F

# Verde (Cian Neón Logo Left)
color2  #00FFFF
color10 #00FFFF

# Amarillo / Naranja (Logo Bottom)
color3  #FF8C00
color11 #FF8C00

# Azul
color4  #007FFF
color12 #007FFF

# Magenta / Púrpura
color5  #BF00FF
color13 #BF00FF

# Cian
color6  #00E5FF
color14 #00E5FF

# Blanco
color7  #FFFFFF
color15 #FFFFFF

# --- Barra de Pestañas ---
tab_bar_edge            top
tab_bar_style           powerline
tab_powerline_style     slanted
active_tab_foreground   #000000
active_tab_background   #00FFFF
inactive_tab_foreground #FFFFFF
inactive_tab_background #222222

# --- Atajos de Teclado ---
enabled_layouts splits
map ctrl+shift+enter launch --location=vsplit
map ctrl+shift+backslash launch --location=hsplit
